version: '3.3'

services:
  web:
    image: chocomoko-web
    restart: unless-stopped
    tty: true
    read_only: true
    tmpfs:
      - /var/lib/nginx
      - /run
    build:
      context: chocomoko-web
      dockerfile: Dockerfile

  lb:
    image: chocomoko-lb
    restart: unless-stopped
    tty: true
    build:
      context: chocomoko-lb
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PROXY_PROTOCOL
      - PROXY_UPSTREAM
    depends_on:
      - "web"

